#pragma checksum "..\..\EditWarnings.xaml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "30F10B270468F3CCC6E870F75F25326296039131"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;
using Work;


namespace Work {
    
    
    /// <summary>
    /// EditWarnings
    /// </summary>
    public partial class EditWarnings : System.Windows.Window, System.Windows.Markup.IComponentConnector {
        
        
        #line 10 "..\..\EditWarnings.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid grid;
        
        #line default
        #line hidden
        
        
        #line 14 "..\..\EditWarnings.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btn_submit;
        
        #line default
        #line hidden
        
        
        #line 19 "..\..\EditWarnings.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btn_delete;
        
        #line default
        #line hidden
        
        
        #line 20 "..\..\EditWarnings.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Calendar cdr_Date;
        
        #line default
        #line hidden
        
        
        #line 21 "..\..\EditWarnings.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox txt_Name;
        
        #line default
        #line hidden
        
        
        #line 22 "..\..\EditWarnings.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lbl_warnColon;
        
        #line default
        #line hidden
        
        
        #line 23 "..\..\EditWarnings.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox dpd_hours;
        
        #line default
        #line hidden
        
        
        #line 24 "..\..\EditWarnings.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox dpd_tt;
        
        #line default
        #line hidden
        
        
        #line 28 "..\..\EditWarnings.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox dpd_Minutes;
        
        #line default
        #line hidden
        
        
        #line 29 "..\..\EditWarnings.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock lbl_title;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/Work;component/editwarnings.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\EditWarnings.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.grid = ((System.Windows.Controls.Grid)(target));
            return;
            case 2:
            this.btn_submit = ((System.Windows.Controls.Button)(target));
            
            #line 14 "..\..\EditWarnings.xaml"
            this.btn_submit.Click += new System.Windows.RoutedEventHandler(this.btn_submit_Click);
            
            #line default
            #line hidden
            return;
            case 3:
            this.btn_delete = ((System.Windows.Controls.Button)(target));
            
            #line 19 "..\..\EditWarnings.xaml"
            this.btn_delete.Click += new System.Windows.RoutedEventHandler(this.btn_delete_Click);
            
            #line default
            #line hidden
            return;
            case 4:
            this.cdr_Date = ((System.Windows.Controls.Calendar)(target));
            
            #line 20 "..\..\EditWarnings.xaml"
            this.cdr_Date.SelectedDatesChanged += new System.EventHandler<System.Windows.Controls.SelectionChangedEventArgs>(this.cdr_Date_SelectedDatesChanged);
            
            #line default
            #line hidden
            return;
            case 5:
            this.txt_Name = ((System.Windows.Controls.TextBox)(target));
            
            #line 21 "..\..\EditWarnings.xaml"
            this.txt_Name.TextChanged += new System.Windows.Controls.TextChangedEventHandler(this.txt_Name_TextChanged_1);
            
            #line default
            #line hidden
            return;
            case 6:
            this.lbl_warnColon = ((System.Windows.Controls.Label)(target));
            return;
            case 7:
            this.dpd_hours = ((System.Windows.Controls.ComboBox)(target));
            
            #line 23 "..\..\EditWarnings.xaml"
            this.dpd_hours.SelectionChanged += new System.Windows.Controls.SelectionChangedEventHandler(this.dpd_hours_SelectionChanged);
            
            #line default
            #line hidden
            return;
            case 8:
            this.dpd_tt = ((System.Windows.Controls.ComboBox)(target));
            
            #line 24 "..\..\EditWarnings.xaml"
            this.dpd_tt.SelectionChanged += new System.Windows.Controls.SelectionChangedEventHandler(this.dpd_tt_SelectionChanged);
            
            #line default
            #line hidden
            return;
            case 9:
            this.dpd_Minutes = ((System.Windows.Controls.ComboBox)(target));
            
            #line 28 "..\..\EditWarnings.xaml"
            this.dpd_Minutes.SelectionChanged += new System.Windows.Controls.SelectionChangedEventHandler(this.dpd_Minutes_SelectionChanged);
            
            #line default
            #line hidden
            return;
            case 10:
            this.lbl_title = ((System.Windows.Controls.TextBlock)(target));
            return;
            }
            this._contentLoaded = true;
        }
    }
}

