#pragma checksum "..\..\MainWindow.xaml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "47661D628043F492B182CC29A9869AFE6C99D9B3"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;
using Work;


namespace Work {
    
    
    /// <summary>
    /// MainWindow
    /// </summary>
    public partial class MainWindow : System.Windows.Window, System.Windows.Markup.IComponentConnector {
        
        
        #line 19 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid grd_Absence;
        
        #line default
        #line hidden
        
        
        #line 21 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lbl_Absences;
        
        #line default
        #line hidden
        
        
        #line 26 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ListBox lst_absences;
        
        #line default
        #line hidden
        
        
        #line 34 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btn_EndAbsense;
        
        #line default
        #line hidden
        
        
        #line 35 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btn_recAbsense;
        
        #line default
        #line hidden
        
        
        #line 36 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox chk_Absence;
        
        #line default
        #line hidden
        
        
        #line 37 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Calendar cdr_abs;
        
        #line default
        #line hidden
        
        
        #line 38 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btn_absenceDate;
        
        #line default
        #line hidden
        
        
        #line 39 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btn_subAbsence;
        
        #line default
        #line hidden
        
        
        #line 40 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lbl_abs_to;
        
        #line default
        #line hidden
        
        
        #line 41 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox dpd_Minutes_In;
        
        #line default
        #line hidden
        
        
        #line 42 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lbl_absColon;
        
        #line default
        #line hidden
        
        
        #line 43 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox dpd_Hour_In;
        
        #line default
        #line hidden
        
        
        #line 44 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox dps_Abs_Tt_In;
        
        #line default
        #line hidden
        
        
        #line 48 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox dpd_Minutes_Out;
        
        #line default
        #line hidden
        
        
        #line 49 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lbl_absColon_Copy;
        
        #line default
        #line hidden
        
        
        #line 50 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox dpd_Hour_Out;
        
        #line default
        #line hidden
        
        
        #line 51 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox dpd_Abs_Tt_Out;
        
        #line default
        #line hidden
        
        
        #line 55 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lbl_abs_reason;
        
        #line default
        #line hidden
        
        
        #line 56 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lbl_abs_reason_Copy;
        
        #line default
        #line hidden
        
        
        #line 57 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox cbx_reas_auto;
        
        #line default
        #line hidden
        
        
        #line 60 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox cbx_reas_man;
        
        #line default
        #line hidden
        
        
        #line 66 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid grd_taken;
        
        #line default
        #line hidden
        
        
        #line 67 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox cbx_item_man;
        
        #line default
        #line hidden
        
        
        #line 72 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox cbx_item_auto;
        
        #line default
        #line hidden
        
        
        #line 75 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ListBox lst_taken;
        
        #line default
        #line hidden
        
        
        #line 83 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btn_TakeItem;
        
        #line default
        #line hidden
        
        
        #line 84 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lbl_Taken;
        
        #line default
        #line hidden
        
        
        #line 89 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox txt_item;
        
        #line default
        #line hidden
        
        
        #line 90 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox chk_Items;
        
        #line default
        #line hidden
        
        
        #line 91 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btn_itemsDate;
        
        #line default
        #line hidden
        
        
        #line 92 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox txt_itemsname;
        
        #line default
        #line hidden
        
        
        #line 93 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock lbl_itemsName;
        
        #line default
        #line hidden
        
        
        #line 94 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Calendar cdr_items;
        
        #line default
        #line hidden
        
        
        #line 95 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btn_subItems;
        
        #line default
        #line hidden
        
        
        #line 96 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox dpd_itemsMinutes;
        
        #line default
        #line hidden
        
        
        #line 97 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lbl_itemsColon;
        
        #line default
        #line hidden
        
        
        #line 98 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox dpd_items_hours;
        
        #line default
        #line hidden
        
        
        #line 99 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox dpd_items_tt;
        
        #line default
        #line hidden
        
        
        #line 107 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Grid grd_Warnings;
        
        #line default
        #line hidden
        
        
        #line 108 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox cbx_warning_Auto;
        
        #line default
        #line hidden
        
        
        #line 112 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox cbx_warn_man;
        
        #line default
        #line hidden
        
        
        #line 116 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ListBox lst_Warnings;
        
        #line default
        #line hidden
        
        
        #line 124 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lbl_Warnings;
        
        #line default
        #line hidden
        
        
        #line 129 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btn_Warning;
        
        #line default
        #line hidden
        
        
        #line 130 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox txt_warning;
        
        #line default
        #line hidden
        
        
        #line 131 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox chk_Warn;
        
        #line default
        #line hidden
        
        
        #line 132 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btn_WarnDate;
        
        #line default
        #line hidden
        
        
        #line 133 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox txt_warnName;
        
        #line default
        #line hidden
        
        
        #line 134 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock lbl_WarnName;
        
        #line default
        #line hidden
        
        
        #line 135 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btn_subWarn;
        
        #line default
        #line hidden
        
        
        #line 136 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Calendar cdr_warnings;
        
        #line default
        #line hidden
        
        
        #line 137 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox dpd_warn_minutes;
        
        #line default
        #line hidden
        
        
        #line 138 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lbl_warnColon;
        
        #line default
        #line hidden
        
        
        #line 139 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox dpd_warn_hours;
        
        #line default
        #line hidden
        
        
        #line 140 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox dpd_warn_tt;
        
        #line default
        #line hidden
        
        
        #line 146 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ListBox lst_workers;
        
        #line default
        #line hidden
        
        
        #line 154 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lbl_name;
        
        #line default
        #line hidden
        
        
        #line 159 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox txt_search;
        
        #line default
        #line hidden
        
        
        #line 164 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btn_AddWorkers;
        
        #line default
        #line hidden
        
        
        #line 165 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btn_print;
        
        #line default
        #line hidden
        
        
        #line 166 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button btn_print_Copy;
        
        #line default
        #line hidden
        
        
        #line 167 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Label lbl_recordNumber;
        
        #line default
        #line hidden
        
        
        #line 168 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox txt_absReason_Copy;
        
        #line default
        #line hidden
        
        
        #line 169 "..\..\MainWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox txt_absReason;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/Work;component/mainwindow.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\MainWindow.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "4.0.0.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.grd_Absence = ((System.Windows.Controls.Grid)(target));
            return;
            case 2:
            this.lbl_Absences = ((System.Windows.Controls.Label)(target));
            return;
            case 3:
            this.lst_absences = ((System.Windows.Controls.ListBox)(target));
            
            #line 26 "..\..\MainWindow.xaml"
            this.lst_absences.MouseDoubleClick += new System.Windows.Input.MouseButtonEventHandler(this.Lst_absences_MouseDoubleClick);
            
            #line default
            #line hidden
            return;
            case 4:
            this.btn_EndAbsense = ((System.Windows.Controls.Button)(target));
            
            #line 34 "..\..\MainWindow.xaml"
            this.btn_EndAbsense.Click += new System.Windows.RoutedEventHandler(this.Btn_EndAbsense_Click);
            
            #line default
            #line hidden
            return;
            case 5:
            this.btn_recAbsense = ((System.Windows.Controls.Button)(target));
            
            #line 35 "..\..\MainWindow.xaml"
            this.btn_recAbsense.Click += new System.Windows.RoutedEventHandler(this.Btn_recAbsense_Click);
            
            #line default
            #line hidden
            return;
            case 6:
            this.chk_Absence = ((System.Windows.Controls.CheckBox)(target));
            
            #line 36 "..\..\MainWindow.xaml"
            this.chk_Absence.Checked += new System.Windows.RoutedEventHandler(this.AbsCheckboxChecked);
            
            #line default
            #line hidden
            
            #line 36 "..\..\MainWindow.xaml"
            this.chk_Absence.Unchecked += new System.Windows.RoutedEventHandler(this.AbsCheckboxUnchecked);
            
            #line default
            #line hidden
            return;
            case 7:
            this.cdr_abs = ((System.Windows.Controls.Calendar)(target));
            
            #line 37 "..\..\MainWindow.xaml"
            this.cdr_abs.SelectedDatesChanged += new System.EventHandler<System.Windows.Controls.SelectionChangedEventArgs>(this.CalendarAbsChosen);
            
            #line default
            #line hidden
            return;
            case 8:
            this.btn_absenceDate = ((System.Windows.Controls.Button)(target));
            
            #line 38 "..\..\MainWindow.xaml"
            this.btn_absenceDate.Click += new System.Windows.RoutedEventHandler(this.Btn_out_Click);
            
            #line default
            #line hidden
            return;
            case 9:
            this.btn_subAbsence = ((System.Windows.Controls.Button)(target));
            
            #line 39 "..\..\MainWindow.xaml"
            this.btn_subAbsence.Click += new System.Windows.RoutedEventHandler(this.Btn_subAbsence_Click);
            
            #line default
            #line hidden
            return;
            case 10:
            this.lbl_abs_to = ((System.Windows.Controls.Label)(target));
            return;
            case 11:
            this.dpd_Minutes_In = ((System.Windows.Controls.ComboBox)(target));
            return;
            case 12:
            this.lbl_absColon = ((System.Windows.Controls.Label)(target));
            return;
            case 13:
            this.dpd_Hour_In = ((System.Windows.Controls.ComboBox)(target));
            return;
            case 14:
            this.dps_Abs_Tt_In = ((System.Windows.Controls.ComboBox)(target));
            return;
            case 15:
            this.dpd_Minutes_Out = ((System.Windows.Controls.ComboBox)(target));
            return;
            case 16:
            this.lbl_absColon_Copy = ((System.Windows.Controls.Label)(target));
            return;
            case 17:
            this.dpd_Hour_Out = ((System.Windows.Controls.ComboBox)(target));
            return;
            case 18:
            this.dpd_Abs_Tt_Out = ((System.Windows.Controls.ComboBox)(target));
            return;
            case 19:
            this.lbl_abs_reason = ((System.Windows.Controls.Label)(target));
            return;
            case 20:
            this.lbl_abs_reason_Copy = ((System.Windows.Controls.Label)(target));
            return;
            case 21:
            this.cbx_reas_auto = ((System.Windows.Controls.ComboBox)(target));
            
            #line 57 "..\..\MainWindow.xaml"
            this.cbx_reas_auto.SelectionChanged += new System.Windows.Controls.SelectionChangedEventHandler(this.cbx_reas_auto_SelectionChanged);
            
            #line default
            #line hidden
            return;
            case 22:
            this.cbx_reas_man = ((System.Windows.Controls.ComboBox)(target));
            
            #line 60 "..\..\MainWindow.xaml"
            this.cbx_reas_man.SelectionChanged += new System.Windows.Controls.SelectionChangedEventHandler(this.cbx_reas_man_SelectionChanged);
            
            #line default
            #line hidden
            return;
            case 23:
            this.grd_taken = ((System.Windows.Controls.Grid)(target));
            return;
            case 24:
            this.cbx_item_man = ((System.Windows.Controls.ComboBox)(target));
            
            #line 67 "..\..\MainWindow.xaml"
            this.cbx_item_man.SelectionChanged += new System.Windows.Controls.SelectionChangedEventHandler(this.cbx_item_man_SelectionChanged);
            
            #line default
            #line hidden
            return;
            case 25:
            this.cbx_item_auto = ((System.Windows.Controls.ComboBox)(target));
            
            #line 72 "..\..\MainWindow.xaml"
            this.cbx_item_auto.SelectionChanged += new System.Windows.Controls.SelectionChangedEventHandler(this.cbx_item_auto_SelectionChanged);
            
            #line default
            #line hidden
            return;
            case 26:
            this.lst_taken = ((System.Windows.Controls.ListBox)(target));
            
            #line 75 "..\..\MainWindow.xaml"
            this.lst_taken.MouseDoubleClick += new System.Windows.Input.MouseButtonEventHandler(this.Lst_taken_MouseDoubleClick);
            
            #line default
            #line hidden
            return;
            case 27:
            this.btn_TakeItem = ((System.Windows.Controls.Button)(target));
            
            #line 83 "..\..\MainWindow.xaml"
            this.btn_TakeItem.Click += new System.Windows.RoutedEventHandler(this.Btn_TakeItem_Click);
            
            #line default
            #line hidden
            return;
            case 28:
            this.lbl_Taken = ((System.Windows.Controls.Label)(target));
            return;
            case 29:
            this.txt_item = ((System.Windows.Controls.TextBox)(target));
            return;
            case 30:
            this.chk_Items = ((System.Windows.Controls.CheckBox)(target));
            
            #line 90 "..\..\MainWindow.xaml"
            this.chk_Items.Checked += new System.Windows.RoutedEventHandler(this.ItemCheckboxChecked);
            
            #line default
            #line hidden
            
            #line 90 "..\..\MainWindow.xaml"
            this.chk_Items.Unchecked += new System.Windows.RoutedEventHandler(this.ItemCheckboxUnchecked);
            
            #line default
            #line hidden
            return;
            case 31:
            this.btn_itemsDate = ((System.Windows.Controls.Button)(target));
            
            #line 91 "..\..\MainWindow.xaml"
            this.btn_itemsDate.Click += new System.Windows.RoutedEventHandler(this.Btn_itemsDate_Click);
            
            #line default
            #line hidden
            return;
            case 32:
            this.txt_itemsname = ((System.Windows.Controls.TextBox)(target));
            return;
            case 33:
            this.lbl_itemsName = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 34:
            this.cdr_items = ((System.Windows.Controls.Calendar)(target));
            
            #line 94 "..\..\MainWindow.xaml"
            this.cdr_items.SelectedDatesChanged += new System.EventHandler<System.Windows.Controls.SelectionChangedEventArgs>(this.CalItemsChosen);
            
            #line default
            #line hidden
            return;
            case 35:
            this.btn_subItems = ((System.Windows.Controls.Button)(target));
            
            #line 95 "..\..\MainWindow.xaml"
            this.btn_subItems.Click += new System.Windows.RoutedEventHandler(this.Btn_subItems_Click);
            
            #line default
            #line hidden
            return;
            case 36:
            this.dpd_itemsMinutes = ((System.Windows.Controls.ComboBox)(target));
            return;
            case 37:
            this.lbl_itemsColon = ((System.Windows.Controls.Label)(target));
            return;
            case 38:
            this.dpd_items_hours = ((System.Windows.Controls.ComboBox)(target));
            return;
            case 39:
            this.dpd_items_tt = ((System.Windows.Controls.ComboBox)(target));
            return;
            case 40:
            this.grd_Warnings = ((System.Windows.Controls.Grid)(target));
            return;
            case 41:
            this.cbx_warning_Auto = ((System.Windows.Controls.ComboBox)(target));
            
            #line 108 "..\..\MainWindow.xaml"
            this.cbx_warning_Auto.SelectionChanged += new System.Windows.Controls.SelectionChangedEventHandler(this.cbx_warning_Auto_SelectionChanged);
            
            #line default
            #line hidden
            return;
            case 42:
            this.cbx_warn_man = ((System.Windows.Controls.ComboBox)(target));
            
            #line 112 "..\..\MainWindow.xaml"
            this.cbx_warn_man.SelectionChanged += new System.Windows.Controls.SelectionChangedEventHandler(this.cbx_warn_man_SelectionChanged);
            
            #line default
            #line hidden
            return;
            case 43:
            this.lst_Warnings = ((System.Windows.Controls.ListBox)(target));
            
            #line 116 "..\..\MainWindow.xaml"
            this.lst_Warnings.MouseDoubleClick += new System.Windows.Input.MouseButtonEventHandler(this.Lst_Warnings_MouseDoubleClick);
            
            #line default
            #line hidden
            return;
            case 44:
            this.lbl_Warnings = ((System.Windows.Controls.Label)(target));
            return;
            case 45:
            this.btn_Warning = ((System.Windows.Controls.Button)(target));
            
            #line 129 "..\..\MainWindow.xaml"
            this.btn_Warning.Click += new System.Windows.RoutedEventHandler(this.Btn_Warning_Click);
            
            #line default
            #line hidden
            return;
            case 46:
            this.txt_warning = ((System.Windows.Controls.TextBox)(target));
            return;
            case 47:
            this.chk_Warn = ((System.Windows.Controls.CheckBox)(target));
            
            #line 131 "..\..\MainWindow.xaml"
            this.chk_Warn.Checked += new System.Windows.RoutedEventHandler(this.WarningCheckboxChecked);
            
            #line default
            #line hidden
            
            #line 131 "..\..\MainWindow.xaml"
            this.chk_Warn.Unchecked += new System.Windows.RoutedEventHandler(this.WarningCheckboxUnchecked);
            
            #line default
            #line hidden
            return;
            case 48:
            this.btn_WarnDate = ((System.Windows.Controls.Button)(target));
            
            #line 132 "..\..\MainWindow.xaml"
            this.btn_WarnDate.Click += new System.Windows.RoutedEventHandler(this.Btn_WarnDate_Click);
            
            #line default
            #line hidden
            return;
            case 49:
            this.txt_warnName = ((System.Windows.Controls.TextBox)(target));
            return;
            case 50:
            this.lbl_WarnName = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 51:
            this.btn_subWarn = ((System.Windows.Controls.Button)(target));
            
            #line 135 "..\..\MainWindow.xaml"
            this.btn_subWarn.Click += new System.Windows.RoutedEventHandler(this.Btn_subWarn_Click);
            
            #line default
            #line hidden
            return;
            case 52:
            this.cdr_warnings = ((System.Windows.Controls.Calendar)(target));
            
            #line 136 "..\..\MainWindow.xaml"
            this.cdr_warnings.SelectedDatesChanged += new System.EventHandler<System.Windows.Controls.SelectionChangedEventArgs>(this.CalendarWarnChosen);
            
            #line default
            #line hidden
            return;
            case 53:
            this.dpd_warn_minutes = ((System.Windows.Controls.ComboBox)(target));
            return;
            case 54:
            this.lbl_warnColon = ((System.Windows.Controls.Label)(target));
            return;
            case 55:
            this.dpd_warn_hours = ((System.Windows.Controls.ComboBox)(target));
            return;
            case 56:
            this.dpd_warn_tt = ((System.Windows.Controls.ComboBox)(target));
            return;
            case 57:
            this.lst_workers = ((System.Windows.Controls.ListBox)(target));
            
            #line 146 "..\..\MainWindow.xaml"
            this.lst_workers.SelectionChanged += new System.Windows.Controls.SelectionChangedEventHandler(this.Lst_workers_SelectionChanged);
            
            #line default
            #line hidden
            
            #line 146 "..\..\MainWindow.xaml"
            this.lst_workers.MouseDoubleClick += new System.Windows.Input.MouseButtonEventHandler(this.Lst_workers_MouseDoubleClick);
            
            #line default
            #line hidden
            return;
            case 58:
            this.lbl_name = ((System.Windows.Controls.Label)(target));
            return;
            case 59:
            this.txt_search = ((System.Windows.Controls.TextBox)(target));
            
            #line 159 "..\..\MainWindow.xaml"
            this.txt_search.TextChanged += new System.Windows.Controls.TextChangedEventHandler(this.Txt_search_TextChanged);
            
            #line default
            #line hidden
            return;
            case 60:
            this.btn_AddWorkers = ((System.Windows.Controls.Button)(target));
            
            #line 164 "..\..\MainWindow.xaml"
            this.btn_AddWorkers.Click += new System.Windows.RoutedEventHandler(this.Btn_AddWorkers_Click);
            
            #line default
            #line hidden
            return;
            case 61:
            this.btn_print = ((System.Windows.Controls.Button)(target));
            
            #line 165 "..\..\MainWindow.xaml"
            this.btn_print.Click += new System.Windows.RoutedEventHandler(this.btn_print_Click);
            
            #line default
            #line hidden
            return;
            case 62:
            this.btn_print_Copy = ((System.Windows.Controls.Button)(target));
            
            #line 166 "..\..\MainWindow.xaml"
            this.btn_print_Copy.Click += new System.Windows.RoutedEventHandler(this.btn_print_Copy_Click);
            
            #line default
            #line hidden
            return;
            case 63:
            this.lbl_recordNumber = ((System.Windows.Controls.Label)(target));
            return;
            case 64:
            this.txt_absReason_Copy = ((System.Windows.Controls.TextBox)(target));
            return;
            case 65:
            this.txt_absReason = ((System.Windows.Controls.TextBox)(target));
            return;
            }
            this._contentLoaded = true;
        }
    }
}

